language: node_js
# run for only for pull requests or master branch
if: 'type = pull_request OR branch = master'
matrix:
  fast_finish: true
  # Generally using active LTS versions here, see https://github.com/nodejs/Release
  include:
    - name: Test client
      node_js: 14
      env: RUN="npm run test:client"
    - name: Test server
      node_js: 14
      env: RUN="npm run test:server"
    - name: Lint and build
      node_js: 14
      env: RUN="npx concurrently --kill-others-on-fail 'npm:lint' 'npm:build:tarball'" DEPLOY="true"
# https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
script: '$RUN'
install: npm ci
dist: bionic
services:
  - mongodb
  - docker
addons:
  apt:
    packages:
      - graphicsmagick
before_script:
  - mongo --version
  - mongod --version
  # Ensure stable NPM version (avoids `-next.0` tags)
  - npm install -g npm
  - ./scripts/ci/update-locales
  - './scripts/ci/fix-weblate public/locales/*/*.json'
cache:
  directories:
    - '$HOME/.node-gyp'
    - '$HOME/.npm'
