# Deploys to Digital Ocean
# After: https://medium.com/swlh/how-to-deploy-your-application-to-digital-ocean-using-github-actions-and-save-up-on-ci-cd-costs-74b7315facc2
name: Deploy & Run
on:
  push:
    branches: [master]

env:
  DOMAIN: dev.refugees.openHospitality.network    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
          key: ${{secrets.SSH_KEY}} # Private key with matching public key authorized to access the server

          script: |
            cd /var/www/$DOMAIN/ft
            git pull
            echo 'Deployment script finished successfully'
