name: Notify matrix when pull request was opened

on:
  workflow_dispatch:
  pull_request:
      types: [opened, reopened]

jobs:
  ping_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "Hello, world!"
          server: "matrix.org"
