name: Notify matrix when pull request was opened

on:
  workflow_dispatch:
  pull_request:
      types: [opened, reopened]
  issues:
      types: [opened, reopened, transferred]
  discussion:
      types: [opened, transferred]

jobs:
  ping_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "${{ github.event.pull_request.user.login }} has just opened a PR: _\"${{ github.event.pull_request.title }}\"_\n
          ${{ github.event.pull_request.html_url }}"
          server: "matrix.org"
